import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faBookDead,
    faCubes,
    faDiceD20,
    faDiceD6,
    faDragon,
    faDungeon,
    faFire,
    faFlask,
    faGem,
    faGhost,
    faHatWizard,
    faQuidditch,
    faRing,
    faRocket,
    faScroll,
    faSkull,
    faSkullCrossbones,
    faSun,
    faMagnifyingGlass,
    faBomb,
    faHeadphones,
    faHeart,
    faCamera,
    faDroplet,
    faMagnet,
    faCrow,
    faCrown,
    faPuzzlePiece,
    faPlane,
    faToilet,
    faOm,
    faStarAndCrescent,
    faCross
} from "@fortawesome/free-solid-svg-icons";

const icons: any = {
    0: faGhost,
    1: faGem,
    2: faFlask,
    3: faCubes,
    4: faSun,
    5: faSkullCrossbones,
    6: faScroll,
    7: faRing,
    8: faHatWizard,
    9: faFire,
    10: faDungeon,
    11: faDragon,
    12: faDiceD6,
    13: faDiceD20,
    14: faBookDead,
    15: faQuidditch,
    16: faSkull,
    17: faRocket,
    18: faBomb,
    19: faMagnifyingGlass,
    20: faHeadphones,
    21: faHeart,
    22: faCamera,
    23: faDroplet,
    24: faCrow,
    25: faCrown,
    26: faOm,
    27: faCross,
    28: faStarAndCrescent,
    29: faMagnet,
    30: faPuzzlePiece,
    31: faToilet,
    32: faPlane
};

export default icons;
